### ISSUE TITLE
/home & /events return 404

### ISSUE THREAD

**Issue by Malvoz** [WebWeWant/webwewant.fyi#6]

**Comment by Malvoz** [comment]
@aarongustafson I silently closed this as it seems it was no longer an issue. But it now is an issue again for /home

**Comment by aarongustafson** [comment]
Can you do a full refresh of your cache. It was a bug in my JavaScript for Eleventy that I fixed a few days back. It should be working though. I'm not seeing an issue.

**Comment by Malvoz** [comment]
That's strange, last time, I cleared all site data but the issue persisted. But indeed it's not an issue after just now clearing the cache.

**Comment by aarongustafson** [comment]
Phew!

**Comment by Malvoz** [comment]
😄 have a good day!

**Comment by Malvoz** [comment]
@aarongustafson FYI I had to clear site data just now to view the latest 10+ Wants on the site... :(

**Comment by aarongustafson** [comment]
The service worker had not changed, but clearly I need to tweak the caching strategy for the wants directory. Sorry about that.

**Comment by marcoscaceres** [comment]
@aarongustafson, happy to review JS/SW code if you need.

**Comment by aarongustafson** [comment]
Thanks @marcoscaceres. I’ll take a look shortly and let you know if I need help.

**Comment by aarongustafson** [comment]
I think this should be resolved now. Let me know if you still see issues @Malvoz.

**Comment by Malvoz** [comment]
Yes it seems so, thanks!
